// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoqlivdqbhxagvvrhyph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvcWxpdmRxYmh4YWd2dnJoeXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjM3MjAsImV4cCI6MjA2MjM5OTcyMH0.W0jTjTGskzZJelfsz3rfTAA8j6NeUDntjPd3NdWAzqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);